timezone: Asia/Shanghai
permalink: /:categories/:title.html
url:

paginate: 12
paginate_path: "page:num"

gems: 
  [jekyll-paginate]

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
